<?php
$result = $conn->query("CREATE TABLE IF NOT EXISTS `documentos_temp_1` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`id_sesion` varchar(100) COLLATE utf8_spanish_ci NOT NULL,
`ip` varchar(15) COLLATE utf8_spanish_ci NOT NULL,
`so` varchar(50) COLLATE utf8_spanish_ci NOT NULL,
`tipo_documento` varchar(3) COLLATE utf8_spanish_ci DEFAULT NULL,
`procedencia` varchar(3) COLLATE utf8_spanish_ci NOT NULL DEFAULT 'tpv',
`tipo_librador` varchar(3) COLLATE utf8_spanish_ci DEFAULT NULL,
`id_librador` int(11) DEFAULT NULL,
`fecha_documento` date DEFAULT NULL,
`fecha_entrada` date DEFAULT NULL,
`fecha_entrega_desde` date DEFAULT NULL,
`fecha_entrega_hasta` date DEFAULT NULL,
`numero_documento` varchar(25) COLLATE utf8_spanish_ci DEFAULT NULL,
`serie_documento` varchar(5) COLLATE utf8_spanish_ci DEFAULT NULL,
`modalidad_pago` varchar(50) COLLATE utf8_spanish_ci DEFAULT NULL,
`modalidad_envio` varchar(50) COLLATE utf8_spanish_ci DEFAULT NULL,
`modalidad_entrega` varchar(50) COLLATE utf8_spanish_ci DEFAULT NULL,
`irpf` double(7,2) DEFAULT NULL,
`importe_irpf` double(15,5) DEFAULT NULL,
`descuento_pp` double(7,2) DEFAULT NULL,
`importe_descuento_pp` double(15,5) DEFAULT NULL,
`descuento_librador` double(7,2) DEFAULT NULL,
`importe_descuento_librador` double(15,5) DEFAULT NULL,
`base` double(15,5) DEFAULT NULL,
`total` double(15,5) DEFAULT NULL,
`estado` tinyint(1) NOT NULL DEFAULT '0',
`entregado` tinyint(1) NOT NULL DEFAULT '0',
`id_usuario` int(10) DEFAULT NULL,
`comensales` smallint(5) DEFAULT NULL,
`hora` time DEFAULT NULL,
`hora_entrega` time NOT NULL DEFAULT '00:00:00',
`id_terminal` int(11) NOT NULL,
PRIMARY KEY (`id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci ROW_FORMAT=DYNAMIC;");

$result = $conn->query("CREATE TABLE IF NOT EXISTS `documentos_temp_2` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`id_documentos_1` int(11) NOT NULL,
`tipo_documento` varchar(3) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`tipo_librador` varchar(3) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`id_librador` int(11) NOT NULL DEFAULT '0',
`slug` varchar(250) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`tipo_producto` tinyint(1) NOT NULL DEFAULT '0',
`fecha` date NOT NULL,
`fecha_entrega_desde` date NOT NULL,
`fecha_entrega_hasta` date NOT NULL,
`id_producto` int(11) NOT NULL DEFAULT '0',
`id_productos_detalles_enlazado` int(11) NOT NULL DEFAULT '0',
`id_productos_detalles_multiples` int(11) NOT NULL DEFAULT '0',
`id_packs` int(11) NOT NULL DEFAULT '0',
`id_productos_relacionados_grupos` int(11) NOT NULL,
`descripcion_productos_relacionados_grupos` varchar(50) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`imagen_producto` varchar(100) COLLATE utf8_spanish_ci NOT NULL,
`descripcion_producto` varchar(250) COLLATE utf8_spanish_ci NOT NULL,
`detalles_producto` varchar(250) COLLATE utf8_spanish_ci NOT NULL,
`descripcion_oferta` varchar(50) COLLATE utf8_spanish_ci NOT NULL,
`codigo_barras_producto` varchar(20) COLLATE utf8_spanish_ci NOT NULL,
`referencia_producto` varchar(20) COLLATE utf8_spanish_ci NOT NULL,
`referencia_librador` varchar(20) COLLATE utf8_spanish_ci NOT NULL,
`numero_serie` varchar(50) COLLATE utf8_spanish_ci NOT NULL,
`lote` varchar(50) COLLATE utf8_spanish_ci NOT NULL,
`caducidad` date NOT NULL,
`cantidad` double(15,5) NOT NULL DEFAULT '0.00000',
`id_unidades` int(11) NOT NULL DEFAULT '0',
`unidad` varchar(5) COLLATE utf8_spanish_ci NOT NULL,
`coste` double(15,5) NOT NULL,
`importe` double(15,5) NOT NULL DEFAULT '0.00000',
`fijo` tinyint(1) NOT NULL DEFAULT '0',
`base_antes_descuento` double(15,5) NOT NULL DEFAULT '0.00000',
`descuento_base` double(7,2) NOT NULL DEFAULT '0.00',
`importe_descuento_base` double(15,5) NOT NULL DEFAULT '0.00000',
`base_despues_descuento` double(15,5) NOT NULL DEFAULT '0.00000',
`iva` double(7,2) NOT NULL DEFAULT '0.00',
`importe_iva` double(15,5) NOT NULL DEFAULT '0.00000',
`recargo` double(7,2) NOT NULL DEFAULT '0.00',
`importe_recargo` double(15,5) NOT NULL DEFAULT '0.00000',
`pvp_unidad` double(15,5) NOT NULL DEFAULT '0.00000',
`pvp_unidad_sin_incrementos` double(15,5) NOT NULL DEFAULT '0.00000',
`total_antes_descuento` double(15,5) NOT NULL DEFAULT '0.00000',
`descuento_total` double(7,2) NOT NULL DEFAULT '0.00',
`importe_descuento_total` double(15,5) NOT NULL DEFAULT '0.00000',
`total_despues_descuento` double(15,5) NOT NULL DEFAULT '0.00000',
`id_documento_2_anterior` int(11) NOT NULL DEFAULT '0',
`id_vendedor` int(11) NOT NULL DEFAULT '0',
`estado` tinyint(1) NOT NULL DEFAULT '0',
`id_usuario` int(10) NOT NULL DEFAULT '0',
`orden` varchar(20) COLLATE utf8_spanish_ci NOT NULL,
`hora` time NOT NULL,
`id_terminal` int(11) NOT NULL DEFAULT '0',
PRIMARY KEY (`id`) USING BTREE,
KEY `id_documento` (`id_documentos_1`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci ROW_FORMAT=DYNAMIC;");

$result = $conn->query("CREATE TABLE IF NOT EXISTS `documentos_temp_iva` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`id_documentos_1` int(11) DEFAULT NULL,
`id_documentos_2` int(11) DEFAULT NULL,
`base` double(15,5) DEFAULT NULL,
`iva` double(7,2) DEFAULT NULL,
`importe_iva` double(15,5) DEFAULT NULL,
`recargo` double(7,2) DEFAULT NULL,
`importe_recargo` double(15,5) DEFAULT NULL,
PRIMARY KEY (`id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci ROW_FORMAT=DYNAMIC;");

$result = $conn->query("CREATE TABLE IF NOT EXISTS `documentos_temp_libradores` (
`id` int(11) unsigned NOT NULL AUTO_INCREMENT,
`id_documentos_1` int(11) DEFAULT NULL,
`codigo_librador` varchar(20) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`nombre` varchar(60) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`apellido_1` varchar(60) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`apellido_2` varchar(60) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`razon_social` varchar(100) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`razon_comercial` varchar(75) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`nif` varchar(20) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`direccion` varchar(90) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`numero` varchar(7) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`escalera` varchar(12) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`piso` varchar(5) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`puerta` varchar(5) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`localidad` varchar(30) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`codigo_postal` varchar(7) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`provincia` varchar(50) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`telefono_1` varchar(12) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`telefono_2` varchar(12) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`fax` varchar(12) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`mobil` varchar(11) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`email` varchar(50) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`persona_contacto` varchar(20) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`banco` varchar(35) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`entidad` varchar(4) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`agencia` varchar(4) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`dc` varchar(2) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`cuenta` varchar(10) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`iban` varchar(24) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`id_tarifa_web` int(11) DEFAULT '0',
`id_tarifa_tpv` int(11) DEFAULT '0',
PRIMARY KEY (`id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;");

$result = $conn->query("CREATE TABLE IF NOT EXISTS `documentos_temp_libradores_envio` (
`id` int(11) unsigned NOT NULL AUTO_INCREMENT,
`id_documentos_1` int(11) DEFAULT NULL,
`fecha_documento` date DEFAULT NULL,
`fecha_envio` date DEFAULT NULL,
`fecha_entrega` date DEFAULT NULL,
`id_librador` int(11) NOT NULL DEFAULT '0',
`nombre` varchar(60) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`apellido_1` varchar(60) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`apellido_2` varchar(60) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`razon_social` varchar(100) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`razon_comercial` varchar(75) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`direccion` varchar(90) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`numero` varchar(7) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`escalera` varchar(12) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`piso` varchar(5) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`puerta` varchar(5) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`localidad` varchar(30) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`codigo_postal` varchar(7) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`provincia` varchar(50) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`zona` varchar(100) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`telefono_1` varchar(12) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`telefono_2` varchar(12) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`mobil` varchar(11) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`persona_contacto` varchar(20) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`observaciones` text COLLATE utf8_spanish_ci,
PRIMARY KEY (`id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;");

$result = $conn->query("CREATE TABLE IF NOT EXISTS `documentos_temp_observaciones` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`id_documentos_1` int(11) NOT NULL,
`id_documentos_2` int(11) NOT NULL,
`id_documentos_combo` int(11) NOT NULL,
`observacion` text COLLATE utf8_spanish_ci NOT NULL,
PRIMARY KEY (`id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;");

$result = $conn->query("CREATE TABLE IF NOT EXISTS `documentos_temp_productos_costes` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`id_documentos_2` int(11) NOT NULL,
`cantidad_base` double(9,3) DEFAULT NULL,
`id_unidades_base` int(11) DEFAULT NULL,
`rentabilidad` double(9,3) DEFAULT NULL,
`id_categoria_elaborados` int(11) DEFAULT NULL,
`tiempo` int(10) DEFAULT NULL,
`coste` double(15,5) NOT NULL DEFAULT '0.00000',
PRIMARY KEY (`id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci ROW_FORMAT=DYNAMIC;");

$result = $conn->query("CREATE TABLE IF NOT EXISTS `documentos_temp_productos_relacionados` (
`id` int(11) unsigned NOT NULL AUTO_INCREMENT,
`id_productos_relacionados` int(11) unsigned NOT NULL DEFAULT '0',
`id_documentos_2` int(11) unsigned NOT NULL DEFAULT '0',
`id_documentos_combo` int(11) unsigned NOT NULL DEFAULT '0',
`id_productos_detalles_enlazado` int(11) unsigned NOT NULL DEFAULT '0',
`id_productos_detalles_multiples` int(11) unsigned NOT NULL DEFAULT '0',
`id_packs` int(11) unsigned NOT NULL DEFAULT '0',
`id_relacionado` int(11) unsigned NOT NULL DEFAULT '0',
`id_titulo_relacionado` int(11) unsigned NOT NULL DEFAULT '0',
`descripcion` varchar(250) COLLATE utf8_spanish_ci NOT NULL DEFAULT '',
`id_grupo` int(11) unsigned NOT NULL DEFAULT '0',
`fijo` tinyint(1) unsigned NOT NULL DEFAULT '1',
`modelo` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '0 - Con / Sin\r\n1 - Normal / Mitad / Sin / Doble\r\n2 - Input cantidad\r\n3 - Unico',
`cantidad_con` double(15,5) NOT NULL DEFAULT '0.00000',
`cantidad_mitad` double(15,5) NOT NULL DEFAULT '0.00000',
`cantidad_sin` double(15,5) NOT NULL DEFAULT '0.00000',
`cantidad_doble` double(15,5) NOT NULL DEFAULT '0.00000',
`sumar_con` double(15,5) NOT NULL DEFAULT '0.00000',
`sumar_mitad` double(15,5) NOT NULL DEFAULT '0.00000',
`sumar_sin` double(15,5) NOT NULL DEFAULT '0.00000',
`sumar_doble` double(15,5) NOT NULL DEFAULT '0.00000',
`por_defecto` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '0-con\r\n1-mitad\r\n2-sin\r\n3-doble',
`mostrar` tinyint(1) unsigned NOT NULL DEFAULT '0',
`orden` varchar(20) COLLATE utf8_spanish_ci DEFAULT NULL,
PRIMARY KEY (`id`) USING BTREE,
KEY `indice` (`id_documentos_2`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci ROW_FORMAT=DYNAMIC;");

$result = $conn->query("CREATE TABLE IF NOT EXISTS `documentos_temp_productos_relacionados_combo` (
`id` int(11) unsigned NOT NULL AUTO_INCREMENT,
`id_documentos_2` int(11) unsigned NOT NULL DEFAULT '0',
`id_productos_detalles_enlazado` int(11) unsigned NOT NULL DEFAULT '0',
`id_productos_detalles_multiples` int(11) unsigned NOT NULL DEFAULT '0',
`id_packs` int(11) unsigned NOT NULL DEFAULT '0',
`id_relacionado` int(11) unsigned NOT NULL DEFAULT '0',
`id_grupo` int(11) unsigned NOT NULL DEFAULT '0',
`fijo` tinyint(1) unsigned NOT NULL DEFAULT '1',
`cantidad` double(15,5) NOT NULL DEFAULT '0.00000',
`sumar` double(15,5) NOT NULL DEFAULT '0.00000',
`mostrar` tinyint(1) unsigned NOT NULL DEFAULT '0',
`orden` varchar(20) COLLATE utf8_spanish_ci DEFAULT NULL,
PRIMARY KEY (`id`) USING BTREE,
KEY `indice` (`id_documentos_2`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci ROW_FORMAT=DYNAMIC;");

$result = $conn->query("CREATE TABLE IF NOT EXISTS `documentos_temp_productos_relacionados_elaborados` (
`id` int(11) unsigned NOT NULL AUTO_INCREMENT,
`id_documentos_2` int(11) unsigned NOT NULL DEFAULT '0',
`id_productos_detalles_enlazado` int(11) unsigned NOT NULL DEFAULT '0',
`id_productos_detalles_multiples` int(11) unsigned NOT NULL DEFAULT '0',
`id_packs` int(11) unsigned NOT NULL DEFAULT '0',
`id_categoria_estadisticas` int(11) unsigned NOT NULL DEFAULT '0',
`id_producto_relacionado` int(11) unsigned NOT NULL DEFAULT '0',
`fijo` tinyint(1) unsigned NOT NULL DEFAULT '1',
`cantidad` double(15,5) NOT NULL DEFAULT '0.00000',
`coste` double NOT NULL DEFAULT '0',
`id_unidad` int(11) unsigned NOT NULL DEFAULT '0',
`sumar` double(15,5) NOT NULL DEFAULT '0.00000',
`mostrar` tinyint(1) unsigned NOT NULL DEFAULT '0',
`orden` varchar(20) COLLATE utf8_spanish_ci DEFAULT NULL,
PRIMARY KEY (`id`) USING BTREE,
KEY `indice` (`id_documentos_2`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci ROW_FORMAT=DYNAMIC;");

$result = $conn->query("CREATE TABLE IF NOT EXISTS `documentos_temp_productos_sku_stock` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`id_producto` int(11) NOT NULL DEFAULT '0',
`id_productos_sku` int(11) NOT NULL DEFAULT '0',
`lote` varchar(20) COLLATE utf8_spanish_ci DEFAULT '',
`caducidad` date DEFAULT NULL,
`numero_serie` varchar(20) COLLATE utf8_spanish_ci DEFAULT '',
`codigo_barras` varchar(20) COLLATE utf8_spanish_ci DEFAULT '',
`tipo_documento` varchar(3) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'ela = elaboración\r\npre = presupuesto\r\nped = pedido\r\nalb = albarán\r\nfac = factura\r\ntiq = tiquet',
`fecha` date DEFAULT NULL,
`id_documento_1` int(11) NOT NULL DEFAULT '0',
`id_documento_2` int(11) NOT NULL DEFAULT '0',
`tipo_librador` varchar(3) COLLATE utf8_spanish_ci DEFAULT NULL,
`id_librador` int(11) DEFAULT '0',
`coste` double(15,5) NOT NULL DEFAULT '0.00000',
`cantidad` double(15,5) NOT NULL DEFAULT '0.00000',
`id_unidades` int(11) NOT NULL DEFAULT '0',
`unidad` varchar(5) COLLATE utf8_spanish_ci NOT NULL,
`importe` double(15,5) NOT NULL DEFAULT '0.00000',
`fecha_alta` date DEFAULT NULL,
`fecha_modificacion` date DEFAULT NULL,
PRIMARY KEY (`id`) USING BTREE,
KEY `lote` (`lote`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci ROW_FORMAT=DYNAMIC;");

$result = $conn->query("CREATE TABLE IF NOT EXISTS `documentos_temp_recibos` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`id_documento` int(11) DEFAULT NULL,
`tipo_documento` varchar(3) COLLATE utf8_spanish_ci NOT NULL,
`id_librador` int(11) DEFAULT NULL,
`importe` double(15,2) DEFAULT NULL,
`fecha` date DEFAULT NULL,
`vencimiento` date DEFAULT NULL,
`pagado` tinyint(1) NOT NULL DEFAULT '0',
`fecha_pago` date DEFAULT NULL,
`hora_pago` time NOT NULL,
`id_banco_caja_ingreso` int(10) NOT NULL DEFAULT '0',
`id_metodo_pago` int(10) NOT NULL DEFAULT '0',
`id_modalidad_pago` int(10) NOT NULL DEFAULT '0',
`numero_efecto` int(10) NOT NULL DEFAULT '1',
`id_usuario_pago` int(10) DEFAULT NULL,
`impreso` tinyint(1) NOT NULL DEFAULT '0',
PRIMARY KEY (`id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci ROW_FORMAT=DYNAMIC;");

$result = $conn->query("SELECT * FROM documentos_numeraciones WHERE ejercicio='2023';");
foreach ($result as $key => $valor) {
    $result = $conn->query("INSERT INTO documentos_numeraciones VALUES(
                                           NULL,
                                           '" . $valor['tipo_documento'] . "',
                                           'temp',
                                           '" . $valor['consecutivo'] . "',
                                           '" . $valor['serie'] . "',
                                           '0');");
}
